import { defineConfig } from 'vitepress';

export default defineConfig({
  title: 'Vue Material 3',
  description: 'Material Design 3 styled components for Vue 3',
  base: '/vue-material-3/',
  head: [
    ['link', { rel: 'preconnect', href: 'https://fonts.googleapis.com' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' }],
    ['link', { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;600;700;900&display=swap' }],
    ['link', { rel: 'stylesheet', href: 'https://fonts.googleapis.com/icon?family=Material+Icons' }],
    ['link', { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined' }],
  ],
  cleanUrls: true,
  ignoreDeadLinks: [/^\/storybook\//],
  lastUpdated: true,
  themeConfig: {
    logo: '/logo.svg',
    nav: [
      { text: 'Guide', link: '/guide/installation' },
      { text: 'Components', link: '/components/' },
      { text: 'API', link: '/api/' },
      { text: 'Migration', link: '/migration/' },
      { text: 'Storybook', link: '/storybook/', target: '_blank' },
    ],
    sidebar: [
      {
        text: 'Guide',
        items: [
          { text: 'Installation', link: '/guide/installation' },
          { text: 'Quick Start', link: '/guide/quick-start' },
          { text: 'Theming', link: '/guide/theming' },
        ],
      },
      {
        text: 'Reference',
        items: [
          { text: 'Components', link: '/components/' },
          { text: 'Autocomplete', link: '/components/autocomplete' },
          { text: 'Avatar', link: '/components/avatar' },
          { text: 'Badge', link: '/components/badge' },
          { text: 'Button', link: '/components/button' },
          { text: 'Card', link: '/components/card' },
          { text: 'Checkbox', link: '/components/checkbox' },
          { text: 'Chips', link: '/components/chips' },
          { text: 'Date Picker', link: '/components/date-picker' },
          { text: 'Dialog', link: '/components/dialog' },
          { text: 'Divider', link: '/components/divider' },
          { text: 'FAB', link: '/components/fab' },
          { text: 'Icon', link: '/components/icon' },
          { text: 'Icon Button', link: '/components/icon-button' },
          { text: 'List', link: '/components/list' },
          { text: 'Menu', link: '/components/menu' },
          { text: 'Navigation', link: '/components/navigation' },
          { text: 'Progress', link: '/components/progress' },
          { text: 'Radio', link: '/components/radio' },
          { text: 'Search', link: '/components/search' },
          { text: 'Segmented Button', link: '/components/segmented-button' },
          { text: 'Select', link: '/components/select' },
          { text: 'Slider', link: '/components/slider' },
          { text: 'Snackbar', link: '/components/snackbar' },
          { text: 'Switch', link: '/components/switch' },
          { text: 'Tabs', link: '/components/tabs' },
          { text: 'Text Field', link: '/components/text-field' },
          { text: 'Time Picker', link: '/components/time-picker' },
          { text: 'Tooltip', link: '/components/tooltip' },
          { text: 'API Reference', link: '/api/' },
          { text: 'Migration Notes', link: '/migration/' },
        ],
      },
    ],
    socialLinks: [{ icon: 'github', link: 'https://github.com/mylmz10/vue-material-3' }],
    search: {
      provider: 'local',
    },
  },
});
